# Generated by Django 3.1 on 2020-08-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctors',
            new_name='doctor',
        ),
    ]
